# -*- coding: utf-8 -*-
"""
VLM Output Parser & Robust Entity Normalization Module
======================================================
This module provides production-grade, fail-safe normalization for raw text/JSON
responses generated by Vision-Language Models (e.g. Qwen2.5-VL, Qwen3-VL)
in the Video Visual Relation Detection (VidVRD) pipeline.

Key Capabilities:
1. Resilient JSON extraction from raw model generation (strips markdown tags,
   conversational filler, and preambles/postscripts).
2. Robust entity extraction supporting diverse VLM formatting outputs:
   - Plain IDs: '[1]', '[2]'
   - Class-annotated IDs: '[1] person', '[3] handbag'
   - Unbracketed numbers: '1', '3'
   - Inverted styles: 'person [1]'
3. Ground-truth detector enrichment: Traverses payload metadata (cluster_info)
   to auto-enrich verified class names for any extracted entity ID.
4. Schema standardization conforming to academic VidVRD benchmarks:
   Exports integer subject/object IDs, semantic class names, validated predicates,
   and visual human-readable labels without risk of downstream parsing crashes.
"""

import re
import json
from typing import Dict, Any, List, Optional, Tuple

# Official VidVRD 26 action relation predicates
VIDVRD_PREDICATES_26 = [
    'bite', 'carry', 'clean', 'cut', 'drive', 'feed', 'get_off', 'get_on', 'grab', 'hit',
    'hold', 'hug', 'kick', 'kiss', 'knock', 'lean_on', 'lick', 'lift', 'play(instrument)',
    'pull', 'push', 'ride', 'shake_hand_with', 'throw', 'touch', 'wave'
]


def clean_vlm_text_to_json(raw_text: str) -> Tuple[Optional[Dict[str, Any]], str]:
    """
    Extracts and parses a JSON object from raw VLM textual output.
    
    Handles:
    - Markdown fenced code blocks (```json ... ``` or ``` ... ```)
    - Preamble greetings or trailing commentary
    - Trailing commas or subtle formatting quirks via regex extraction
    
    Returns:
    - (parsed_json_dict, cleaned_text_str) if successful, or (None, cleaned_text_str) if parsing failed.
    """
    if not raw_text or not isinstance(raw_text, str):
        return None, ""

    clean_text = raw_text.strip()

    # 1. Strip markdown code fence blocks if present
    if '```json' in clean_text:
        clean_text = clean_text.split('```json')[-1].split('```')[0].strip()
    elif '```' in clean_text:
        clean_text = clean_text.split('```')[-1].split('```')[0].strip()

    # 2. Extract strictly the outermost JSON object boundaries using regex
    json_match = re.search(r'\{.*\}', clean_text, re.DOTALL)
    if json_match:
        clean_text = json_match.group(0).strip()

    try:
        parsed = json.loads(clean_text)
        if isinstance(parsed, dict):
            return parsed, clean_text
        elif isinstance(parsed, list):
            return {"triplets": parsed}, clean_text
        return None, clean_text
    except Exception:
        return None, clean_text


def build_entities_map_from_payload(payload_data: Dict[str, Any]) -> Dict[int, str]:
    """
    Extracts verified detector entity mappings from a cluster payload dictionary.
    
    Returns:
    - A dictionary mapping integer entity IDs to their verified detector class names:
      e.g. {1: 'person', 2: 'person', 3: 'handbag', 4: 'backpack'}
    """
    entities_map: Dict[int, str] = {}
    if not isinstance(payload_data, dict):
        return entities_map

    # Check cluster_info -> entities
    entities_list = payload_data.get("cluster_info", {}).get("entities", [])
    if not entities_list and "entities" in payload_data:
        entities_list = payload_data["entities"]

    for ent in entities_list:
        if isinstance(ent, dict):
            m_id = ent.get("mark_id", ent.get("id", ""))
            cls = ent.get("class_label", ent.get("class", ""))
            m = re.search(r'\d+', str(m_id))
            if m and cls:
                entities_map[int(m.group(0))] = str(cls).strip().lower()

    return entities_map


def normalize_entity(entity_val: Any, entities_map: Optional[Dict[int, str]] = None) -> Dict[str, Any]:
    """
    Normalizes any subject or object string into a robust structured entity dictionary.
    
    Guarantees zero-crash resilience against arbitrary VLM string representations.
    
    Returns:
    {
        'id': int or None,
        'class': str,
        'display': str (e.g. '[1] person')
    }
    """
    if entities_map is None:
        entities_map = {}

    if entity_val is None:
        return {'id': None, 'class': 'unknown', 'display': 'None'}

    val_str = str(entity_val).strip()
    if not val_str:
        return {'id': None, 'class': 'unknown', 'display': 'None'}

    # 1. Attempt extracting integer ID: prioritize bracketed '[ID]', then standalone word boundary '\b\d+\b'
    id_match = re.search(r'\[(\d+)\]', val_str) or re.search(r'\b(\d+)\b', val_str)

    if id_match:
        ent_id = int(id_match.group(1))
        # Look up verified detector class first
        ent_class = entities_map.get(ent_id)
        if not ent_class:
            # Fallback: extract any leftover alphabetic text from the VLM string
            cleaned_text = re.sub(r'\[\d+\]|\b\d+\b|[\(\)\[\]:]', ' ', val_str).strip()
            ent_class = cleaned_text.lower() if cleaned_text else 'unknown'

        return {
            'id': ent_id,
            'class': ent_class,
            'display': f'[{ent_id}] {ent_class}'
        }
    else:
        # Extreme edge case: VLM returned text without any recognizable numeric ID
        cleaned_text = re.sub(r'[\[\]\(\)]', '', val_str).strip().lower()
        cls_name = cleaned_text if cleaned_text else 'unknown'
        return {
            'id': None,
            'class': cls_name,
            'display': f'[?] {cls_name}'
        }


def parse_and_normalize_vlm_output(
    raw_output: str,
    payload_data: Dict[str, Any],
    valid_predicates: Optional[List[str]] = None
) -> Dict[str, Any]:
    """
    Main entry point for normalizing raw VLM text generation for a cluster.
    
    Parameters:
    - raw_output: Raw string output decoded from VLM generation.
    - payload_data: The cluster payload dictionary containing 'cluster_info'.
    - valid_predicates: Allowed predicate list (defaults to VIDVRD_PREDICATES_26).
    
    Returns:
    {
        'cluster_id': str,
        'triplets': List[Dict[str, Any]],
        'is_valid_json': bool,
        'raw_output': str
    }
    """
    if valid_predicates is None:
        valid_predicates = VIDVRD_PREDICATES_26

    cluster_name = payload_data.get("cluster_info", {}).get("cluster_id", "default_cluster")
    parsed_json, clean_text = clean_vlm_text_to_json(raw_output)

    entities_map = build_entities_map_from_payload(payload_data)
    normalized_triplets: List[Dict[str, Any]] = []

    if parsed_json is not None:
        raw_triplets = parsed_json.get("triplets", [])
        if not isinstance(raw_triplets, list):
            raw_triplets = [raw_triplets] if isinstance(raw_triplets, dict) else []

        for trip in raw_triplets:
            if not isinstance(trip, dict):
                continue

            sub_info = normalize_entity(trip.get("subject"), entities_map)
            obj_info = normalize_entity(trip.get("object"), entities_map)
            rel = str(trip.get("relation", "")).strip().lower()
            rsn = str(trip.get("reason", "")).strip()

            is_valid = rel in valid_predicates
            status = "[OK]" if is_valid else "[X] Invalid"

            normalized_triplets.append({
                "subject": sub_info["display"],
                "subject_id": sub_info["id"],
                "subject_class": sub_info["class"],
                "relation": rel,
                "object": obj_info["display"],
                "object_id": obj_info["id"],
                "object_class": obj_info["class"],
                "status": status,
                "reason": rsn
            })

        return {
            "cluster_id": cluster_name,
            "triplets": normalized_triplets,
            "is_valid_json": True,
            "raw_output": clean_text
        }
    else:
        return {
            "cluster_id": cluster_name,
            "triplets": [],
            "is_valid_json": False,
            "raw_output": raw_output
        }


def format_triplets_table(normalized_triplets: List[Dict[str, Any]]) -> str:
    """
    Renders an aligned, human-readable ASCII table summarizing normalized triplets.
    """
    col_sub = 18
    col_rel = 16
    col_obj = 18
    col_stat = 10

    lines = []
    lines.append("-" * 90)
    lines.append(f"{'Subject':<{col_sub}} | {'Relation':<{col_rel}} | {'Object':<{col_obj}} | {'Status':<{col_stat}} | Reason / Explanation")
    lines.append("-" * 90)

    if not normalized_triplets:
        lines.append(f"{'None':<{col_sub}} | {'None':<{col_rel}} | {'None':<{col_obj}} | {'[EMPTY]':<{col_stat}} | Khong phat hien quan he tuong tac nao trong cum nay")
    else:
        for t in normalized_triplets:
            lines.append(f"{t['subject']:<{col_sub}} | {t['relation']:<{col_rel}} | {t['object']:<{col_obj}} | {t['status']:<{col_stat}} | {t['reason']}")

    lines.append("-" * 90)
    return "\n".join(lines)
